default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: guidd
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1

development:
  <<: *default
  database: terreiro_umbanda

test:
  <<: *default
  database: terreiro_umbanda_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
